server:
  adminConnectors: []
  applicationConnectors:
    - type: http
      port: ${PORT:-8080}

logging:
  level: INFO
  loggers:
    com.myth: DEBUG
  appenders:
  - type: file
    currentLogFilename: "./mobile-server.log"
    threshold: ALL
    archive: true
    archivedLogFilenamePattern: "./target/logs/mobile-server-%d.log.gz"
    archivedFileCount: 5
    timeZone: UTC
    logFormat: "%date{YYYY-MM-dd HH:mm:ss} %logger{15} %thread %C %M %X{applicationId:--} %X{requestId:--} uid:%X{userId:--} %msg%n %xException"

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: ${MYSQL_USERNAME:-root}
  # the password
  password: ${MYSQL_PASSWORD:-root}
  # the JDBC URL
  url: jdbc:mysql://${MYSQL_ENDPOINT:-127.0.0.1}/mobile_server_prod
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 32
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

swagger:
  includeSwaggerResource: true
  resourcePackage: com.myth.resources

serverContextConfig:
  mysqlReadWriteThreadCount: 55

jwtTokenSecret: secrettoken

redis:
  endpoint: ${REDIS_ENDPOINT:-localhost:6379}
  password: null
  minIdle: 0
  maxIdle: 0
  maxTotal: 1924
  ssl: false
  timeout: 2000

environment: qa